[tool.poetry]
name = "vector-db"
version = "0.1.0"
description = ""
authors = ["nuj <nuj@socar.kr>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
